server: 
  port: 9909
spring:
  rabbitmq: 
      host: 192.168.0.80
      port: 5672
      username: admin
      password: 123456
aliyun:
   sms:
      accessKeyId: 
      accessKeySecret: 
      template_code: 
      sign_name: 
