server: 
  port: 9909
spring:
  rabbitmq: 
      host: 192.168.0.80
      port: 5672
      username: admin
      password: 123456
aliyun:
   sms:
      accessKeyId: LTAIX38F9HO1Ljg0
      accessKeySecret: G8Uq9aqIV1z0WlKJ5FrVx62CGaOaN5
      template_code: SMS_165108322
      sign_name: 微风