server: 
   port: 9066
   
logging:
   level:
      cn.tan: debug
      # org.springframework: debug 
# 连接四大参数
spring:
   application:
      name: file-server #指定服务名
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver #  可省略，SpringBoot自动推断
      # Java 与 MySQL 的 13 个小时时差,serverTimezone=GMT%2B8 或者 serverTimezone=Hongkong
      url: jdbc:mysql://0.0.0.0:3306/news?characterEncoding=UTF8&serverTimezone=GMT%2B8
      username: root
      password: 123456,
   jpa:
      database: MySQL
      show-sql: true
      # 连接池配置
      hikari:
         idle-timeout: 60000
         maximum-pool-size: 30
         minimum-idle: 10 
   redis:
     host: 192.168.0.103
     #host: 127.0.0.1
     port: 6379
   http:
      multipart:
      #maxFileSize 单个数据大小
         maxFileSize: 200Mb     
         #maxRequestSize 是总数据大小    
         maxRequestSize: 500Mb
ai: #语料库目录 
   dataPath : D:\\data\\article         
   #浏览器标记

jwt:
   config:
      key: fengshenme
      ttl: 3600000

#mybatis: 
   #configuration: 
      #map-underscore-to-camel-case: true
   # 别名扫描
   # type-aliases-package: cn.tan.upload.entity
   # mapper.xml文件位置,如果没有映射文件，请注释掉
   #mapper-locations: classpath:mapper/*.xml  
   
aliyun:
   sms:
      accessKeyId: 0 # 填自个的阿里云短信key
      accessKeySecret: 0
      template_code: 0
      sign_name: 0
      
# 文件存储目录      
storessd:
   #filepath : "D:/img"
   filepath : "/usr/local/file"
