server: 
   port: 9066
   compression:
       enabled: true
       mime-types: image/png,image/jpeg,image/jpg,video/mp4,text/html,application/javascript,text/css,application/octet-stream,application/json
   
logging:
   level:
      tan.wei: debug
      root: INFO
   file: ./logs/sshfileupload.log
   
      # org.springframework: debug 
# 连接四大参数
spring:
   application:
      name: fileshen #指定服务名
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver #  可省略，SpringBoot自动推断
      # Java 与 MySQL 的 13 个小时时差,serverTimezone=GMT%2B8 或者 serverTimezone=Hongkong
      url: jdbc:mysql://0.0.0.0:3306/news?characterEncoding=UTF8&serverTimezone=GMT%2B8
      username: 
      password: 
      hikari:
           idle-timeout: 60000
           maximum-pool-size: 30
           minimum-idle: 10 
   jpa:
      show-sql: true
      # 连接池配置
   redis:
     host: 192.168.0.67
     port: 6379
     password: 258011
   http:
    multipart:
    #maxFileSize 单个数据大小
    max-file-size: 200Mb  
    #maxRequestSize 是总数据大小
    max-request-size: 500Mb

jwt.config:
      key: fengshenme
      ttl: 3600000 
       
   
aliyun.sms:
     accessKeyId: 
     accessKeySecret: 
     template_code: 
     sign_name: 
      
# 文件存储目录      
storessd:
   filepath : "H:/img"

   