server: 
   port: 9055
   
# 连接四大参数
spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver #  可省略，SpringBoot自动推断
      url: jdbc:mysql://192.168.0.103:33306/article_one?characterEncoding=UTF8
      username: root
      password: 998673x
   jpa:
      database: MySQL
      show-sql: true
      # 连接池配置
      hikari:
         idle-timeout: 60000
         maximum-pool-size: 30
         minimum-idle: 10  
ai: #语料库目录 
   dataPath : D:\\data\\article         
        